<?php
require_once '/var/www/test/src/Model/Domain/DataHandler.php';
require_once 'db.php';

?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cinema</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
    <style type="text/css">
        body {
            font: 14px sans-serif;
            text-align: center;
            background-image: url("https://www.verdict.co.uk/wp-content/uploads/2017/10/shutterstock_384996514.jpg");
            background-repeat: no-repeat;
            background-attachment: fixed;
            height: 100%;
            background-size: cover;
            background-position: center;
        }

        table {
            background-color: #ffcccc;
            border: 1px solid black;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
            position: fixed;
            top: 0;
            width: 100%;
        }

        li {
            float: left;
            border-right: 1px solid #bbb;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: #111;
        }

        .topnav {
            overflow: hidden;
            background-color: #333;
        }

        .topnav a {
            float: left;
            color: #ffb3b3;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .pagination {
            display: inline-block;
        }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
            border: 1px solid #ddd;
            margin: 0 4px;
            background-color: lightpink;
        }

        .pagination a.active {
            background-color: #ffb3b3;
            color: white;
        }

        .pagination a:hover:not(.active) {
            background-color: #ddd;
        }

        }
        .center {
            text-align: center;
        }

        .tooltip {
            position: relative;
            display: inline-block;
            border-bottom: 1px dotted black; /* If you want dots under the hoverable text */
        }
    </style>
</head>
<body>
<div class="page-header">
    <div class="topnav">
        <ul>
            <li><a href="/src/View/Login/homepage.phtml">Homepage</a></li>
            <li><a href="/src/View/Login/schedule.php">Schedule</a></li>
            <li><a href="/src/View/Login/login.php">Log In</a></li>
        </ul>
    </div>
    <h1 style="color:#b30000;"> Welcome to our movie booking site!</h1>
</div>


<p1><?php $d = new DataHandler();
    $d->paginateMovies($pdo); ?></p1>
</div>
<div class="center">
    <div class="pagination">
        <a href="#">&laquo;</a>
        <a href="#">1</a>
        <a href="#">2</a>
        <a href="#">3</a>
        <a href="#">4</a>
        <a href="#">5</a>
        <a href="#">6</a>
        <a href="#">&raquo;</a>
    </div>
</div>
</body>
</html>